
export const USER_POKEMON_LIST = [
  { name: "Aromatisse", types: ["Fairy"] },
  { name: "Corviknight", types: ["Flying", "Steel"] },
  { name: "Espathra", types: ["Psychic"] },
  { name: "Espeon", types: ["Psychic"] },
  { name: "Flareon", types: ["Fire"] },
  { name: "Glaceon", types: ["Ice"] },
  { name: "Gliscor", types: ["Ground", "Flying"] },
  { name: "Hisuian Zoroark", types: ["Normal", "Ghost"] },
  { name: "Hitmonlee", types: ["Fighting"] },
  { name: "Jolteon", types: ["Electric"] },
  { name: "Leafeon", types: ["Grass"] },
  { name: "Malamar", types: ["Dark", "Psychic"] },
  { name: "Mightyena", types: ["Dark"] },
  { name: "Mr Mime", types: ["Psychic", "Fairy"] },
  { name: "Pinsir", types: ["Bug"] },
  { name: "Rhydon", types: ["Rock", "Ground"] },
  { name: "Sandslash", types: ["Ground"] },
  { name: "Shedinja", types: ["Bug", "Ghost"] },
  { name: "Stakataka", types: ["Rock", "Steel"] },
  { name: "Togekiss", types: ["Fairy", "Flying"] },
  { name: "Umbreon", types: ["Dark"] },
  { name: "Vaporeon", types: ["Water"] },
  { name: "Weezing", types: ["Poison"] }
];

export const TYPE_COLORS = {
  Normal: "bg-gray-400 text-white",
  Fighting: "bg-red-700 text-white",
  Flying: "bg-indigo-300 text-black",
  Poison: "bg-purple-500 text-white",
  Ground: "bg-yellow-600 text-white",
  Rock: "bg-yellow-800 text-white",
  Bug: "bg-lime-500 text-black",
  Ghost: "bg-violet-800 text-white",
  Fire: "bg-orange-500 text-white",
  Water: "bg-blue-500 text-white",
  Grass: "bg-green-500 text-white",
  Electric: "bg-yellow-400 text-black",
  Psychic: "bg-pink-500 text-white",
  Ice: "bg-cyan-300 text-black",
  Dragon: "bg-indigo-700 text-white",
  Dark: "bg-gray-800 text-white",
  Steel: "bg-slate-400 text-black",
  Fairy: "bg-pink-300 text-black"
};

export const TYPE_CHART = {
  Normal: { Rock: 0.5, Ghost: 0, Steel: 0.5 },
  Fighting: { Normal: 2, Flying: 0.5, Poison: 0.5, Rock: 2, Bug: 0.5, Ghost: 0, Psychic: 0.5, Ice: 2, Dark: 2, Steel: 2, Fairy: 0.5 },
  Flying: { Fighting: 2, Rock: 0.5, Bug: 2, Grass: 2, Electric: 0.5, Steel: 0.5 },
  Poison: { Poison: 0.5, Ground: 0.5, Rock: 0.5, Ghost: 0.5, Grass: 2, Steel: 0, Fairy: 2 },
  Ground: { Flying: 0, Poison: 2, Rock: 2, Bug: 0.5, Fire: 2, Grass: 0.5, Electric: 2, Steel: 2 },
  Rock: { Fighting: 0.5, Flying: 2, Ground: 0.5, Bug: 2, Fire: 2, Ice: 2, Steel: 0.5 },
  Bug: { Fighting: 0.5, Flying: 0.5, Poison: 0.5, Ghost: 0.5, Fire: 0.5, Grass: 2, Psychic: 2, Dark: 2, Steel: 0.5, Fairy: 0.5 },
  Ghost: { Normal: 0, Ghost: 2, Psychic: 2, Dark: 0.5, Steel: 0.5 },
  Fire: { Rock: 0.5, Bug: 2, Fire: 0.5, Water: 0.5, Grass: 2, Ice: 2, Dragon: 0.5, Steel: 2 },
  Water: { Ground: 2, Rock: 2, Fire: 2, Water: 0.5, Grass: 0.5, Dragon: 0.5 },
  Grass: { Flying: 0.5, Poison: 0.5, Ground: 2, Rock: 2, Bug: 0.5, Fire: 0.5, Water: 2, Grass: 0.5, Dragon: 0.5, Steel: 0.5 },
  Electric: { Flying: 2, Ground: 0, Water: 2, Grass: 0.5, Electric: 0.5, Dragon: 0.5 },
  Psychic: { Fighting: 2, Poison: 2, Psychic: 0.5, Dark: 0, Steel: 0.5 },
  Ice: { Flying: 2, Ground: 2, Fire: 0.5, Water: 0.5, Grass: 2, Ice: 0.5, Dragon: 2, Steel: 0.5 },
  Dragon: { Dragon: 2, Steel: 0.5, Fairy: 0 },
  Dark: { Fighting: 0.5, Ghost: 2, Psychic: 2, Dark: 0.5, Fairy: 0.5 },
  Steel: { Rock: 2, Fire: 0.5, Water: 0.5, Electric: 0.5, Ice: 2, Steel: 0.5, Fairy: 2 },
  Fairy: { Fighting: 2, Poison: 0.5, Fire: 0.5, Dragon: 2, Dark: 2, Steel: 0.5 }
};
